spring:
  redis:
    host: localhost
    port: 6379
    password: 2486
    jedis:
      pool:
        max-idle: 10
        min-idle: 2
        max-active: 20
        max-wait: -1

  datasource:
    url: jdbc:mysql://localhost:3306/humphrey
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.model
