spring:
  redis:
    host: ${REDIS_HOST:root}
    port: 6379
    password: ${REDIS_PASSWORD:2486}
    jedis:
      pool:
        max-idle: 10
        min-idle: 2
        max-active: 20
        max-wait: -1

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/${DATABASENAME}
    username: ${DBUSERNAME:root}
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.model
